### PR TITLE
[fix] Fix the bug of variable “num_blocks in FCM

### PR DESCRIPTION
**Pull request by querryton**

### CODE REVIEW

**Review by cdliang11 — APPROVED** [review]

**Comment by cdliang11** [comment]
Good!

**Comment by JiJiJiang** [comment]
Nice catch!

**Comment by cdliang11** [comment]
https://github.com/alibaba-damo-academy/3D-Speaker/blob/ebf090f8e21ad325bb4f42177ea770f4a1f93e12/speakerlab/models/campplus/DTDNN.py#L13-L26

Hi @querryton , there is the same bug in 3D speaker, you can help fix it.

**Comment by querryton** [comment]
> https://github.com/alibaba-damo-academy/3D-Speaker/blob/ebf090f8e21ad325bb4f42177ea770f4a1f93e12/speakerlab/models/campplus/DTDNN.py#L13-L26
> 
> Hi @querryton , there is the same bug in 3D speaker, you can help fix it.

https://github.com/alibaba-damo-academy/3D-Speaker/pull/97
Done.

**Pull request merged**
