### PR TITLE
[uio] update filter and filter configuration

### PR DESCRIPTION
**Pull request by czy97**

### CODE REVIEW

**Comment by JiJiJiang** [comment]
To keep the same naming scheme as the ``shuffle``, ``speed_perturb`` and ``spec_aug`` flags in the configs, rename ‘use_filter’ as simply 'filter' could be better.

**Review by JiJiJiang — COMMENTED** [review]
as above

**Comment by czy97** [comment]
> To keep the same naming scheme as the `shuffle`, `speed_perturb` and `spec_aug` flags in the configs, rename ‘use_filter’ as simply 'filter' could be better.

Done.

**Review by Hunterhuan — APPROVED** [review]
nice job

**Pull request merged**
